name: Laravel Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    
    - name: Verify MariaDB connection
      run: mysql -D test -e 'SELECT VERSION()'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.github', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Install npm dependencies
      run: npm install
      
    - name: Compile assets
      run: npm run build
      
    - name: Run migrations
      run: php artisan migrate

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php artisan test
