name: Laravel Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    services:
       mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Verify MariaDB connection
      run: mysql -u root -e 'SELECT version()'
      
    - name: Create MariaDB database
      run: mysql -u root -e 'CREATE DATABASE test'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.github', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Install npm dependencies
      run: npm install
      
    - name: Compile assets
      run: npm run build
      
    - name: Run migrations
      run: php artisan migrate

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php artisan test
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
        DB_USERNAME: root
